---
- name: Test role
  hosts: 127.0.0.1
  connection: local
  become: true

  vars_files:
    - defaults/main.yml

  tasks:
    - name: Include main task
      ansible.builtin.include_tasks: tasks/main.yml
      vars:
        upgrade_packages_reboot_if_needed: false
