---
- name: All-in-one local installation playbook
  hosts: localhost

  tasks:
    - name: Include all .yml with variables
      ansible.builtin.include_vars:
        dir: vars
        depth: 1
        ignore_unknown_extensions: true
        extensions:
          - 'yml'
      tags: [always]

    - name: Upgrade
      ansible.builtin.import_tasks: tasks/upgrade.yml
      become: true
      tags: [upgrade]

    - name: Check if bash installed
      ansible.builtin.stat:
        path: ~/.bashrc
      register: bashrc_file
      tags: [always]

    - name: Check if zsh installed
      ansible.builtin.stat:
        path: ~/.zshrc
      register: zshrc_file
      tags: [always]

    - name: Setting host facts using complex arguments
      ansible.builtin.set_fact:
        bashrc: "{{ bashrc_file.stat.exists }}"
        zshrc: "{{ zshrc_file.stat.exists }}"
      tags: [always]

    - name: Add shell aliases
      ansible.builtin.import_tasks: tasks/shell_aliases.yml
      tags: [aliases]

    - name: Add custom hosts to /etc/hosts
      ansible.builtin.import_tasks: tasks/hosts.yml
      tags: [hosts]

    - name: chrome
      ansible.builtin.import_tasks: tasks/chrome.yml
      tags: [chrome]

    - name: Configure PATH environment variable
      ansible.builtin.lineinfile:
        path: ~/.zshrc
        line: 'export PATH=$HOME/bin:/usr/local/bin:$PATH'
      when: zshrc
      tags: [always]

    - name: Install linux tools
      ansible.builtin.import_tasks: tasks/tools.yml
      tags: [tools]

    - name: Clone git repositories
      ansible.builtin.import_tasks: tasks/reps.yml
      tags: [reps]

    - name: Docker
      ansible.builtin.import_tasks: tasks/docker.yml
      tags: [docker]
      become: true

    - name: JetBrains Toolbox App
      ansible.builtin.import_tasks: tasks/toolbox.yml
      tags: [toolbox]

    - name: Sublime Text
      ansible.builtin.import_tasks: tasks/sublime.yml
      tags: [sublime]

    - ansible.builtin.import_tasks: tasks/terraform.yml
      tags: [terraform]

    - ansible.builtin.import_tasks: tasks/packer.yml
      tags: [packer]

    - name: terragrunt
      ansible.builtin.import_tasks: tasks/terragrunt.yml
      tags: [terragrunt]

    - name: kubectl
      ansible.builtin.import_tasks: tasks/kubectl.yml
      tags: [kubectl]

    - name: k9s
      ansible.builtin.import_tasks: tasks/k9s.yml
      tags: [k9s]

    - name: krew
      ansible.builtin.import_tasks: tasks/krew.yml
      tags: [krew]

    - name: YandexCloud
      ansible.builtin.import_tasks: tasks/yc.yml
      tags: [yc]

    - name: helm
      ansible.builtin.import_tasks: tasks/helm.yml
      tags: [helm]

    # - ansible.builtin.import_tasks: tasks/minikube.yml
    #  tags: [minikube]

    - name: JenkinsX
      ansible.builtin.import_tasks: tasks/jx.yml
      tags: [jx]

    - name: isio ctl
      ansible.builtin.import_tasks: tasks/istioctl.yml
      tags: [istioctl]

    - name: direnv
      ansible.builtin.import_tasks: tasks/direnv.yml
      tags: [direnv]

    - name: VSCode
      ansible.builtin.import_tasks: tasks/vscode.yml
      tags: [vscode]

    - name: Dive
      ansible.builtin.import_tasks: tasks/dive.yml
      tags: [dive]

    - name: Telegram
      ansible.builtin.import_tasks: tasks/telegram.yml
      tags: [telegram]
