---
- name: All-in-one local installation playbook
  hosts: localhost

  vars_files:
    - vars/reps.yml

  tasks:
    - name: Check if bash installed
      ansible.builtin.stat:
        path: ~/.bashrc
      register: bashrc_file
      tags: [ always ]

    - name: Check if zsh installed
      ansible.builtin.stat:
        path: ~/.zshrc
      register: zshrc_file
      tags: [ always ]
    
    - name: Setting host facts using complex arguments
      ansible.builtin.set_fact:
        bashrc: "{{ bashrc_file.stat.exists }}"
        zshrc: "{{ zshrc_file.stat.exists }}"
      tags: [ always ]

    - name: chrome
      import_tasks: tasks/chrome.yml
      tags: [ chrome ]

    - name: Configure PATH environment variable
      ansible.builtin.lineinfile:
        path: ~/.zshrc
        line: 'export PATH=$HOME/bin:/usr/local/bin:$PATH'
      when: zshrc
      tags: [ always ]

    - name: Install linux tools
      import_tasks: tasks/tools.yml
      tags: [ tools ]

    - name: Clone git repositories
      import_tasks: tasks/reps.yml
      tags: [ reps ]
    
    - import_tasks: tasks/docker.yml
      tags: [ docker ]
      become: true

    # - ansible.builtin.include: tasks/sublime.yml
    #   tags: [ sublime ]

    # - ansible.builtin.include: tasks/terraform.yml
    #   tags: [ terraform ]

    - ansible.builtin.include: tasks/kubectl.yml
      tags: [ kubectl ]

    - ansible.builtin.include: tasks/krew.yml
      tags: [ krew ]

    - ansible.builtin.include: tasks/yc.yml
      tags: [ yc ]

    - ansible.builtin.include: tasks/helm.yml
      tags: [ helm ]

    - ansible.builtin.include: tasks/minikube.yml
      tags: [ minikube ]

    - ansible.builtin.include: tasks/jx.yml
      tags: [ jx ]

