# direnv is an extension for your shell. It augments existing shells with a new feature that can load
# and unload environment variables depending on the current directory.
# https://direnv.net/
# https://github.com/direnv/direnv
---
- name: direnv | Install direnv
  ansible.builtin.shell: curl -sfL https://direnv.net/install.sh | bash
  environment:
    bin_path: /usr/local/bin
  become: true

- name: direnv | hook direnv into your bash shell
  when: bashrc
  block:
    - ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: eval "$(direnv hook bash)"

    - ansible.builtin.blockinfile:
        path: ~/.bashrc
        block: |
          show_virtual_env() {
            if [[ -n "$VIRTUAL_ENV" && -n "$DIRENV_DIR" ]]; then
              echo "($(basename $VIRTUAL_ENV))"
            fi
          }
          export -f show_virtual_env
          PS1='$(show_virtual_env)'$PS1 


- name: direnv | hook direnv into your zsh shell
  when: zshrc
  block:
    - ansible.builtin.lineinfile:
        path: ~/.zshrc
        line: eval "$(direnv hook zsh)"

    - ansible.builtin.blockinfile:
        path: ~/.zshrc
        block: |
          setopt PROMPT_SUBST

          show_virtual_env() {
            if [[ -n "$VIRTUAL_ENV" && -n "$DIRENV_DIR" ]]; then
              echo "($(basename $VIRTUAL_ENV))"
            fi
          }
          PS1='$(show_virtual_env)'$PS1
