# Docker Engine is an open source containerization technology for building and containerizing your applications.
# https://docs.docker.com/engine/install/
---
- name: docker | Run docker role
  ansible.builtin.include_role:
    name: geerlingguy.docker
  vars:
    docker_users: ["{{ ansible_user_id }}"]
    docker_install_compose: true

# ToDo: No docker group for user

- name: docker | python packages
  ansible.builtin.include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - docker
      - docker-compose