---
- name: HashiCorp | Ubuntu/Debian
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  become: true
  block:
    - name: HashiCorp | prerequisites
      ansible.builtin.package:
        name:
          - gnupg
          - software-properties-common
          - curl
        state: latest
    - name: HashiCorp | add repository keys
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /etc/apt/trusted.gpg.d/hashicorp.asc
        mode: '0644'
        force: true
    - name: HashiCorp | add repository
      ansible.builtin.apt_repository:
        repo: "deb https://apt.releases.hashicorp.com {{ ansible_facts['lsb']['codename'] }} main"
        state: present
        filename: hashicorp

- name: HashiCorp | CentOS/RHEL
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'
  become: true
  block:
    - name: HashiCorp | prerequisites
      ansible.builtin.package:
        name: yum-utils
        state: latest
    - name: HashiCorp | Add repository
      ansible.builtin.yum_repository:
        name: hashicorp
        description: Hashicorp YUM repo
        baseurl: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: HashiCorp | Fedora
  when: ansible_distribution == 'Fedora'
  become: true
  block:
    - name: HashiCorp | prerequisites
      ansible.builtin.package:
        name: dnf-plugins-core
        state: latest
    - name: HashiCorp | Add repository
      ansible.builtin.command:
        cmd: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
        warn: false
      args:
        creates: /etc/yum.repos.d/hashicorp.repo

- name: HashiCorp | Amazon Linux
  when: ansible_distribution == 'Amazon'
  become: true
  block:
    - name: HashiCorp | prerequisites
      ansible.builtin.package:
        name: yum-utils
        state: latest
    - name: HashiCorp | Add repository
      ansible.builtin.yum_repository:
        name: hashicorp
        description: Hashicorp repo
        baseurl: https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
