---
- name: hosts | Add hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ item.ip }}    "
    line: "{{ item.ip }}    {{ item.hosts | join(' ') }}"
    owner: root
    group: root
    mode: '0644'
  become: true
  with_items: "{{ additional_hosts }}"
