# https://jenkins-x.io/v3/admin/setup/jx3/
---
- name: jx | Get latest release of jx
  community.general.github_release:
    user: jenkins-x
    repo: jx
    action: latest_release
  register: latest_jx

- name: "jx | Installing jx {{ latest_jx.tag }}"
  ansible.builtin.unarchive:
    src: "https://github.com/jenkins-x/jx/releases/download/{{ latest_jx.tag }}/jx-linux-amd64.tar.gz"
    include: jx
    dest: /usr/local/bin
    mode: 0755
    remote_src: yes
  become: yes

