# KVM (Kernel-based Virtual Machine) is the leading open source virtualisation technology for Linux.
# https://www.linux-kvm.org/page/Main_Page
# https://ubuntu.com/blog/kvm-hyphervisor
---
- name: kvm | Check if Virtualization is enabled
  ansible.builtin.shell: egrep -c '(vmx|svm)' /proc/cpuinfo
  register: proc_cpuinfo
  failed_when:
    - proc_cpuinfo.rc == 0
    - proc_cpuinfo.stdout | int == 0

- name: kvm | Install packages
  ansible.builtin.package:
    name:
      - cpu-checker
      # An opensource emulator and virtualization package that provides hardware emulation.
      - qemu-kvm
      # A package that provides configuration files required to run the libvirt daemon.
      - libvirt-daemon-system
      # A set of command-line utilities for provisioning and modifying virtual machines.
      - virtinst
      # A set of client-side libraries and APIs for managing and controlling virtual machines & hypervisors from the command line.
      - libvirt-clients
      # A set of tools for creating and managing bridge devices.
      - bridge-utils
    state: latest
  become: yes

- name: kvm | kvm-ok
  ansible.builtin.shell: kvm-ok
  register: kvm_ok_result
  failed_when:
    - kvm_ok_result.rc == 0
    - "'KVM acceleration can be used' not in kvm_ok_result.stdout"
