# packer - is a free and open source tool for creating golden images for multiple platforms from a single source configuration.
# https://www.packer.io/docs
---
- name: Packer | Package repositories
  ansible.builtin.import_tasks: tasks/hashicorp.yml

- name: Packer | Install packer
  ansible.builtin.package:
    name: packer
    state: latest
  become: true

- name: Packer | Enable Tab completion
  ansible.builtin.shell: packer -autocomplete-install
  # ignore when: "already installed"
  ignore_errors: true
