# Clone git-repositories from list
---
- name: Reps | Loop over repos
  ansible.builtin.include_tasks: tasks/reps/clone_repositories.yml
  with_items: '{{ reps }}'
  loop_control:
     loop_var: grouped_repos
