# Sublime Text - the sophisticated text editor for code, markup and prose
# https://www.sublimetext.com/docs/linux_repositories.html
---
- name: sublime | Debian/Ubuntu
  block:
  - name: prerequisites
    ansible.builtin.package:
      name:
        - apt-transport-https
      state: latest

  - name: sublime | Install repositories
    ansible.builtin.apt_key:
      url: https://download.sublimetext.com/sublimehq-pub.gpg
      state: present
    become: yes

  - name: sublime | Add repository
    ansible.builtin.apt_repository:
      repo: deb https://download.sublimetext.com/ apt/stable/
      filename: sublime-text.list
      state: present
    become: yes
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  become: yes


- name: sublime | CentOS/RHEL
  block:
    - name: sublime | prerequisites
      ansible.builtin.package:
        name: yum-utils
        state: latest

    - name: sublime | Add repository
      ansible.builtin.yum_repository:
        name: sublime-text
        description: sublime-text stable YUM repo
        baseurl: https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
        gpgkey: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
        gpgcheck: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'
  become: true


- name: sublime | Fedora
  block:
    - name: sublime | prerequisites
      ansible.builtin.package:
        name: dnf-plugins-core
        state: latest

    - name: sublime | Add repository key
      ansible.builtin.rpm_key:
        state: present
        key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg

    - name: sublime | Add repository
      ansible.builtin.command:
        cmd: dnf config-manager --add-repo https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo 
        warn: false
      args:
        creates: /etc/yum.repos.d/hashicorp.repo
  when: ansible_distribution == 'Fedora'
  become: true


- name: sublime | Install pre-required packages
  ansible.builtin.package:
    name:
      - dirmngr
      - gnupg
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: latest
  become: yes

- name: sublime | Install sublime-text
  ansible.builtin.package:
    name:
      - sublime-text
    state: latest
    update_cache: yes
  become: yes
