# Sublime Text - the sophisticated text editor for code, markup and prose
# https://www.sublimetext.com/docs/linux_repositories.html
---
- name: Sublime | Debian/Ubuntu
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  become: true
  block:
  - name: Sublime | prerequisites
    ansible.builtin.package:
      name:
        - apt-transport-https
      state: latest

  - name: Sublime | add repository keys
    ansible.builtin.get_url:
      url: https://download.sublimetext.com/sublimehq-pub.gpg
      dest: /etc/apt/trusted.gpg.d/sublime.asc
      mode: '0644'
      force: true

  - name: Sublime | Add repository
    ansible.builtin.apt_repository:
      repo: "deb https://download.sublimetext.com/ apt/stable/"
      filename: sublime
      state: present
    become: true


- name: Sublime | CentOS/RHEL
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'
  become: true
  block:
    - name: Sublime | prerequisites
      ansible.builtin.package:
        name: yum-utils
        state: latest

    - name: Sublime | Add repository
      ansible.builtin.yum_repository:
        name: sublime-text
        description: sublime-text stable YUM repo
        baseurl: https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
        gpgkey: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
        gpgcheck: true

- name: Sublime | Fedora
  when: ansible_distribution == 'Fedora'
  become: true
  block:
    - name: Sublime | prerequisites
      ansible.builtin.package:
        name: dnf-plugins-core
        state: latest

    - name: Sublime | Add repository key
      ansible.builtin.rpm_key:
        state: present
        key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg

    - name: Sublime | Add repository
      ansible.builtin.command:
        cmd: dnf config-manager --add-repo https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
        warn: false
      args:
        creates: /etc/yum.repos.d/hashicorp.repo

- name: Sublime | Install pre-required packages
  ansible.builtin.package:
    name:
      - dirmngr
      - gnupg
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: latest
  become: true

- name: Sublime | Install sublime-text
  ansible.builtin.package:
    name:
      - sublime-text
    state: latest
    update_cache: true
  become: true
