---
- name: telegram | Downloading telegram
  ansible.builtin.unarchive:
    src: "https://telegram.org/dl/desktop/linux"
    include: Telegram/Telegram
    dest: /tmp
    remote_src: yes
    extra_opts: [--strip-components=1]
  become: yes

- name: telegram | copy
  ansible.builtin.copy:
    src: /tmp/Telegram
    dest: /usr/local/bin/telegram
    mode: 0755
    force: yes

- name: telegram | remove temp files
  ansible.builtin.file:
    path: /tmp/Telegram
    state: absent
