---
- name: Telegram | Downloading telegram
  ansible.builtin.unarchive:
    src: "https://telegram.org/dl/desktop/linux"
    include: Telegram/Telegram
    dest: /tmp
    remote_src: true
    extra_opts: [--strip-components=1]
  become: true

- name: Telegram | copy
  ansible.builtin.copy:
    src: /tmp/Telegram
    dest: /usr/local/bin/telegram
    mode: 0755
    force: true

- name: Telegram | remove temp files
  ansible.builtin.file:
    path: /tmp/Telegram
    state: absent
