# Terragrunt is a thin wrapper that provides extra tools for keeping your configurations DRY,
# working with multiple Terraform modules, and managing remote state.
# https://terragrunt.gruntwork.io/docs/getting-started/install/
---
- name: terragrunt | Get latest release of terragrunt
  community.general.github_release:
    user: gruntwork-io
    repo: terragrunt
    action: latest_release
  register: latest_terragrunt

- name: "terragrunt | Installing terragrunt {{ latest_terragrunt.tag }}"
  ansible.builtin.get_url:
    url: "https://github.com/gruntwork-io/terragrunt/releases/download/{{ latest_terragrunt.tag }}/terragrunt_linux_amd64"
    dest: /usr/local/bin/terragrunt
    mode: '0755'
  become: yes
