---
# terraform - is an open-source infrastructure as code software tool that provides a consistent CLI workflow to manage hundreds of cloud services.
# https://www.terraform.io/docs

- name: Terraform | Package repositories
  ansible.builtin.import_tasks: tasks/hashicorp.yml
  become: true

- name: Terraform | Install terraform
  ansible.builtin.package:
    name: terraform
    state: latest
  become: true

- name: Terraform | Enable Tab completion
  ansible.builtin.shell: terraform -install-autocomplete
  # ignore when: "already installed"
  ignore_errors: true
