---
# terraform - is an open-source infrastructure as code software tool that provides a consistent CLI workflow to manage hundreds of cloud services.
# https://www.terraform.io/docs

- name: Terraform | Ubuntu/Debian
  block:
    - name: Terraform | prerequisites
      ansible.builtin.package:
        name:
          - gnupg
          - software-properties-common
          - curl
        state: latest
    - name: Terraform | add repository keys
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
    - name: Terraform | add repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main
        state: present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  become: true


- name: Terraform | CentOS/RHEL
  block:
    - name: Terraform | prerequisites
      ansible.builtin.package:
        name: yum-utils
        state: latest
    - name: Terraform | Add repository
      ansible.builtin.yum_repository:
        name: hashicorp
        description: Hashicorp YUM repo
        baseurl: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'
  become: true


- name: Terraform | Fedora
  block:
    - name: Terraform | prerequisites
      ansible.builtin.package:
        name: dnf-plugins-core
        state: latest
    - name: Terraform | Add repository
      ansible.builtin.command:
        cmd: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo 
        warn: false
      args:
        creates: /etc/yum.repos.d/hashicorp.repo
  when: ansible_distribution == 'Fedora'
  become: true


- name: Terraform | Amazon Linux
  block:
    - name: Terraform | prerequisites
      ansible.builtin.package:
        name: yum-utils
        state: latest
    - name: Terraform | Add repository
      ansible.builtin.yum_repository:
        name: hashicorp
        description: Hashicorp repo
        baseurl: https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  when: ansible_distribution == 'Amazon'
  become: true


- name: Terraform | Install terraform
  ansible.builtin.package:
    name: terraform
    state: latest
  become: true

- name: Terraform | Enable Tab completion
  ansible.builtin.shell: terraform -install-autocomplete
  # ignore when: "already installed"
  ignore_errors: yes
