---
- name: Tools | Install packages
  ansible.builtin.package:
    name:
      # https://git-scm.com/
      - git
      # https://www.vim.org/
      - vim
      # https://github.com/scop/bash-completion
      - bash-completion
      - curl
      # jq is a lightweight and flexible command-line JSON processor.
      # https://jqlang.github.io/jq/
      - jq
      # htop - an interactive process viewer
      # https://htop.dev/
      - htop
      - net-tools
      # Generic Colouriser
      # https://github.com/garabik/grc
      - grc
      - make
    state: latest
  become: true

- name: Tools | Set vim as the default editor
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: "export EDITOR={{ default_editor }}"
  when: bashrc

- name: Tools | Set vim as the default editor
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: "export EDITOR={{ default_editor }}"
  when: zshrc
