- name: tools | Install packages
  ansible.builtin.package:
    name:
      - git
      - vim
      - bash-completion
      - curl
      - jq
    state: latest
  become: yes

- name: tools | Set vim as the default editor
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: 'export EDITOR=vim'
  when: bashrc

- name: tools | Set vim as the default editor
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: 'export EDITOR=vim'
  when: zshrc