---
- name: Tools | Install packages
  ansible.builtin.package:
    name:
      - git
      - vim
      - bash-completion
      - curl
      - jq
      - htop
    state: latest
  become: true

- name: Tools | Set vim as the default editor
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: "export EDITOR={{ default_editor }}"
  when: bashrc

- name: Tools | Set vim as the default editor
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: "export EDITOR={{ default_editor }}"
  when: zshrc
