# JetBrains Toolbox App
# Manage your IDEs the easy way
# https://www.jetbrains.com/toolbox-app/download/download-thanks.html?platform=linux
---
- name: Toolbox | Install pre-requisites
  ansible.builtin.package:
    name:
      - libfuse2
  become: true

- name: Toolbox | Get latest release
  ansible.builtin.uri:
    url: https://data.services.jetbrains.com/products/releases?code=TBA&latest=true&type=release
    http_agent: 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'
    headers:
      Origin: 'https://www.jetbrains.com'
      Accept-Encoding: 'gzip, deflate, br'
      Accept-Language: 'en-US,en;q=0.8'
      Accept: 'application/json, text/javascript, */*; q=0.01'
      Referer: 'https://www.jetbrains.com/toolbox/download/'
      Connection: 'keep-alive'
      DNT: '1'
    return_content: true
  register: toolbox_latest_release

- name: Toolbox | Check current version
  ansible.builtin.shell: /usr/local/bin/jetbrains-toolbox --version
  ignore_errors: true
  register: toolbox_version

- name: Toolbox | Installation block
  when:
    - toolbox_version.rc > 0
    - toolbox_latest_release.json.TBA[0].build not in toolbox_version.stdout
  block:
    - name: Toolbox | Get checksum
      ansible.builtin.uri:
        url: "{{ toolbox_latest_release.json.TBA[0].downloads.linux.checksumLink }}"
        return_content: true
        force: true
      register: checksum

    - name: "Toolbox | download {{ toolbox_latest_release.json.TBA[0].downloads.linux.link }}"
      ansible.builtin.get_url:
        url: "{{ toolbox_latest_release.json.TBA[0].downloads.linux.link }}"
        checksum: "sha256:{{ checksum.content[:64] }}"
        dest: /tmp/jetbrains-toolbox.tar.gz
        force: true
        mode: 0644

    - name: Toolbox | unarchive
      ansible.builtin.unarchive:
        src: /tmp/jetbrains-toolbox.tar.gz
        dest: /tmp

    - name: "Toolbox | /tmp/jetbrains-toolbox-{{ toolbox_latest_release.json.TBA[0].build }}/jetbrains-toolbox"
      ansible.builtin.copy:
        src: "/tmp/jetbrains-toolbox-{{ toolbox_latest_release.json.TBA[0].build }}/jetbrains-toolbox"
        dest: /usr/local/bin/jetbrains-toolbox
        mode: 0755
        owner: "{{ ansible_user_id }}"
      become: true

    - name: Toolbox | Remove jetbrains-toolbox archive
      ansible.builtin.file:
        path: /tmp/jetbrains-toolbox.tar.gz
        state: absent

    - name: Toolbox | Remove jetbrains-toolbox archive
      ansible.builtin.file:
        path: "/tmp/jetbrains-toolbox-{{ toolbox_latest_release.json.TBA[0].build }}"
        state: absent
