# Visual Studio Code is a lightweight but powerful source code editor
# https://code.visualstudio.com/docs/
---
- name: vscode | install VSCode
  block:

  - block:
    - name: vscode | Install gpg
      ansible.builtin.apt:
        name:
          - wget
          - gpg
          - apt-transport-https
        state: latest
        update_cache: true

    - name: vscode | Add an Apt signing kye
      ansible.builtin.apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        keyring: /etc/apt/keyrings/packages.microsoft.gpg
        state: present

    - name: vscode | Add repository into sources list
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
        state: present
        filename: vscode.list

    - name: vscode | Install VSCode
      ansible.builtin.apt:
        name: code
        state: latest
        update_cache: true
    when: vscode_install_from_rep

  - block:
    - name: VSCode | Install from .deb
      ansible.builtin.apt:
        deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
    when: not vscode_install_from_rep

  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and vscode_install_from_rep
  become: yes


- name: vscode | install VSCode
  block:

  - block:
    - name: sublime | Add repository key
      ansible.builtin.rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

  #sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

    - name: vscode | Install VSCode
      ansible.builtin.apt:
        name: code
        state: latest
        update_cache: true
    when: vscode_install_from_rep

  - block:
    - name: VSCode | Install from .rpm
      ansible.builtin.apt:
        deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-rpm-x64
    when: not vscode_install_from_rep

  when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'
  become: yes



- name: vscode | Install extensions
  ansible.builtin.shell: "code --install-extension {{ item }}"
  with_items: "{{ vscode_extensions }}"

- name: vscode | List extensions
  ansible.builtin.shell: "code --list-extensions --show-versions"
  register: vscode_extensions

- debug: var=vscode_extensions.stdout_lines