---
- name: Verify
  hosts: all

  vars:
    host_timezone: "{{ lookup('file','/etc/timezone') }}"
  vars_files:
    - ../../defaults/main.yml

  tasks:
    - name: Test host timezone
      ansible.builtin.assert:
        that: ntp_timezone == host_timezone
