---
- name: Setup RedHat
  ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Setup Debian
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Reboot task
  ansible.builtin.include_tasks: reboot.yml
  when: upgrade_packages_reboot_if_needed and reboot_required | default(false)
