---
- name: Reboot the server
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: upgrade_packages_reboot_if_needed|bool == true and reboot_required|bool == true

- name: Check the uptime post reboot
  ansible.builtin.shell: uptime
  register: UPTIME_POST_REBOOT
  when: upgrade_packages_reboot_if_needed|bool == true and reboot_required|bool == true

- ansible.builtin.debug:
    msg: "{{ UPTIME_POST_REBOOT.stdout }}"
  when: upgrade_packages_reboot_if_needed|bool == true and reboot_required|bool == true
