---
- name: Update apt repositories
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 86400

- name: Upgrade all apt packages
  ansible.builtin.apt:
    upgrade: dist
    force_apt_get: yes
  when: upgrade_packages_all|bool == true

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Check if a reboot is required after upgrade
  register: reboot_required_file
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_md5: no
  when: upgrade_packages_reboot_if_needed|bool == true

- name: Set reboot_required variable
  ansible.builtin.set_fact:
    reboot_required: true
  when: reboot_required_file.stat.exists
