---
- name: Update apt repositories
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 86400

- name: Upgrade all apt packages
  ansible.builtin.apt:
    upgrade: dist
    force_apt_get: true
  when: upgrade_packages_all

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: true

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true

- name: Check if a reboot is required after upgrade
  register: reboot_required_file
  ansible.builtin.stat:
    path: /var/run/reboot-required
  when: upgrade_packages_reboot_if_needed

- name: Set reboot_required variable
  ansible.builtin.set_fact:
    reboot_required: true
  when: upgrade_packages_reboot_if_needed and reboot_required_file.stat.exists
