---
- name: Upgrade all dnf packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  when: upgrade_packages_all and ansible_facts['pkg_mgr'] == 'dnf'

- name: Add needs-restarting utility
  ansible.builtin.dnf:
    name: dnf-utils
    state: latest
  when: upgrade_packages_reboot_if_needed and ansible_facts['pkg_mgr'] == 'dnf'

- name: Upgrade all yum packages
  ansible.builtin.yum:
    name: "*"
    state: latest
  when: upgrade_packages_all and ansible_facts['pkg_mgr'] == 'yum'

- name: Add needs-restarting utility
  ansible.builtin.yum:
    name: yum-utils
    state: latest
  when: upgrade_packages_reboot_if_needed and ansible_facts['pkg_mgr'] == 'yum'

- name: Check if a reboot is required after upgrade
  ansible.builtin.command: "/usr/bin/needs-restarting -r"
  register: reboot_required
  ignore_errors: true
  changed_when: false
  failed_when: reboot_required.rc == 2
  when: upgrade_packages_reboot_if_needed

- name: Set reboot_required variable
  ansible.builtin.set_fact:
    reboot_required: true
  when: upgrade_packages_reboot_if_needed and reboot_required.rc == 1
